name: Build

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-baseline-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install dependencies
        run: |
          sudo apt-get update -qq && sudo apt-get -y install \
          build-essential \
          cmake
        
      - name: Build xeve baseline
        run: |
          mkdir build
          cd build
          cmake .. -DSET_PROF=BASE
          make
          
      - name: 'Upload executable Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: xeveb_app-linux-artifact
          path: build/bin/xeveb_app
          retention-days: 5
          
      - name: 'Upload library Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: libxeveb-linux-artifact
          path: build/lib/
          retention-days: 5

  build-main-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: install dependencies
        run: |
          sudo apt-get update -qq && sudo apt-get -y install \
          build-essential \
          cmake
          
      - name: Build xeve main
        run: |
          mkdir build
          cd build
          cmake ..
          make
          
          echo "ls ---------------------"
          ls
          echo "src_base ---------------------"
          cd src_base
          ls
          echo "Release ---------------------"
          cd Release
          ls
          
      - name: 'Upload executable Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: xeve_app-linux-artifact
          path: build/bin/xeve_app
          retention-days: 5
          
      - name: 'Upload library Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: libxeve-linux-artifact
          path: build/lib/
          retention-days: 5
          
  build-baseline-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build xeve baseline
        run: |
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles" -DSET_PROF=BASE
          make
                 
      - name: 'Upload executable Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: xeveb_app.exe-windows-artifact
          path: build/bin/xeveb_app.exe
          retention-days: 5
          
      - name: 'Upload library Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: xeveb.dll-windows-artifact
          path: build/src_base/Release/xeveb.dll
          retention-days: 5
          
      - name: 'Upload import-library Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: xeveb.lib-windows-artifact
          path: build/src_base/static/lib/Release/xeveb.lib
          retention-days: 5

  build-main-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build xeve main
        run: |
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles"
          make
          
      - name: 'Upload executable Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: xeve_app.exe-windows-artifact
          path: build/bin/xeve_app.exe
          retention-days: 5
          
      - name: 'Upload library Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: xeve.dll-windows-artifact
          path: build/src_base/Release/xeve.dll
          retention-days: 5
          
      - name: 'Upload import-library Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: xeve.lib-windows-artifact
          path: build/src_base/static/lib/Release/xeve.lib
          retention-days: 5
