# This workfow is responsbile for creating deb package and upload it to launchpad.net

name: Launchpad

on:
  workflow_dispatch:

jobs:
  launchpad:

    strategy:
      matrix:
        profile: [base, main]

    runs-on: ubuntu-latest

    # Here golbal variables are set!
    env:
      maintainer_mail: "dariusz.frankiewicz@gmail.com"
      debemail: "dariusz.frankiewicz@gmail.com"
      debfullname: "MPEG_5"
      PPA_URL: "https://launchpad.net/~mpeg5/+archive/ubuntu/xeve"

    steps:
    
    - name: Get sources
      id: vars
      run: |
      
        #Get tag
        TAG=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest | grep "tag_name" | awk -F\" '{print $4}' | cut -c2-)
        echo "TAG=$TAG" >> $GITHUB_OUTPUT

        LOCATION=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest | grep "tarball_url" | awk -F\" '{print $4}')

        #Download file
        curl -L -o xeve-${{matrix.profile}}-$TAG.tar.gz $LOCATION

        tar -xvf xeve-${{matrix.profile}}-$TAG.tar.gz
        rm xeve-${{matrix.profile}}-$TAG.tar.gz
        #TODO: change below line to mpeg5-xeve-*
        mv *-xeve-* xeve-${{matrix.profile}}-$TAG
        tar -czf xeve-${{matrix.profile}}-$TAG.tar.gz xeve-${{matrix.profile}}-$TAG

        echo "Package created form TAG: $TAG :bookmark:" >> $GITHUB_STEP_SUMMARY

    - name: Install dependencies
      run: |
        sudo apt install packaging-dev gnupg

    - name: Prepare package (dh_make)
      run: |
        cd xeve-${{matrix.profile}}-${{ steps.vars.outputs.TAG }}

        DEBEMAIL=${{ env.debemail }}
        DEBFULLNAME=${{ env.debfullname }}
        export DEBEMAIL DEBFULLNAME
        dh_make -f ../xeve-${{matrix.profile}}-${{ steps.vars.outputs.TAG }}.tar.gz -c bsd -e ${{ env.maintainer_mail }} --createorig -l -y

        echo "Debemail in package: ${{ env.debemail }}  :email:" >> $GITHUB_STEP_SUMMARY
        echo "Debfullname in package: ${{ env.debfullname }}  :speech_balloon:" >> $GITHUB_STEP_SUMMARY

    - name: Edit sources (${{matrix.profile}})
      # TODO: Files from this step have to be later integrated with project repository, they shouldn't be fetched from external repo
      run: |
        cd xeve-${{matrix.profile}}-${{ steps.vars.outputs.TAG }}/debian

        curl -o changelog https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/${{matrix.profile}}/debian/changelog
        curl -o compat https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/${{matrix.profile}}/debian/compat
        curl -o control https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/${{matrix.profile}}/debian/control
        curl -o copyright https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/${{matrix.profile}}/debian/copyright
        curl -o README.source https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/${{matrix.profile}}/debian/README.source
        curl -o rules https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/${{matrix.profile}}/debian/rules
        curl -o xeve-${{matrix.profile}}-dev.install https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/${{matrix.profile}}/debian/xeve-${{matrix.profile}}-dev.install
        curl -o xeve-${{matrix.profile}}1.install https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/${{matrix.profile}}/debian/xeve-${{matrix.profile}}1.install 

        #Remove example and template files
        rm -rf *.ex
    
    - name: 'Upload executable Artifact - ${{matrix.profile}}'
      if: ${{ false }}
      uses: actions/upload-artifact@v3
      with:
        name: download-1-${{matrix.profile}}
        path: xeve*
        retention-days: 1

    - name: Prepare gpg key
      # https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow
      run:  |
        echo -e "${{ secrets.GPG_KEY }}" | gpg --import
        gpg --list-keys

    - name: Debuild
      run: |
        cd xeve-${{matrix.profile}}-${{ steps.vars.outputs.TAG }}

        DEBEMAIL=${{ env.debemail }}
        DEBFULLNAME=${{ env.debfullname }}
        export DEBEMAIL DEBFULLNAME
        debuild -S -sa -k${{secrets.GPG_KEY_ID}}

        # OR
        # dpkg-buildpackage --build=source --no-sign
        # debsign -k ${{ secrets.GPG_KEY_ID }} ../xeve-${{matrix.profile}}_${{ steps.vars.outputs.TAG }}-1ubuntu1.dsc

    - name: 'Upload Package files - ${{matrix.profile}}'
      if: ${{ false }}
      uses: actions/upload-artifact@v3
      with:
        name: download-2-${{matrix.profile}}
        path: xeve*
        retention-days: 1

    - name: Push package to launchpad
      run: |
        dput -u -s ppa:mpeg5/xeve xeve-${{matrix.profile}}_${{ steps.vars.outputs.TAG }}-1ubuntu1_source.changes
        echo "Package - ${{matrix.profile}}, placed on: ${{ env.PPA_URL }}  :globe_with_meridians:" >> $GITHUB_STEP_SUMMARY

    - name: Upload logs on fail
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: Build failure logs
        path: ${{ runner.temp }}/*