# This workfow is responsbile for creating deb package and upload it to launchpad.net

name: Launchpad

on:
  workflow_dispatch:

jobs:
  launchpad:
    runs-on: ubuntu-latest

    # Here golbal variables are set!
    env:
      maintainer_mail: "maintainer@example.com"
      debmail: "maintainer@example.com"
      debfullname: "MPEG-5_EVC"

    steps:
    
    - name: Get sources
      id: vars
      run: |
      
        #Get tag
        TAG=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest | grep "tag_name" | awk -F\" '{print $4}' | cut -c2-)
        echo "TAG=$TAG" >> $GITHUB_OUTPUT

        LOCATION=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest | grep "tarball_url" | awk -F\" '{print $4}')

        #Download file
        curl -L -o xeve-base-$TAG.tar.gz $LOCATION
        # curl -L -o xeve-main-$TAG.tar.gz $LOCATION

        tar -xvf xeve-base-$TAG.tar.gz
        rm xeve-base-$TAG.tar.gz
        mv dariusz-f-xeve-bf119a8 xeve-base-$TAG
        tar -czf xeve-base-$TAG.tar.gz xeve-base-$TAG

        pwd
        ls -al

        echo "Package created form TAG: $TAG :bookmark:" >> $GITHUB_STEP_SUMMARY

    - name: Install dependencies
      run: |
        sudo apt install packaging-dev gnupg

    - name: Prepare package
      run: |
        cd xeve-base-${{ steps.vars.outputs.TAG }}
        
        pwd
        ls -al
        
        # cd xeve-main-${{ steps.vars.outputs.TAG }}

        DEBMAIL=${{ env.debmail }}
        DEBFULLNAME=${{ env.debfullname }}
        export DEBEMAIL DEBFULLNAME
        dh_make -f ../xeve-base-${{ steps.vars.outputs.TAG }}.tar.gz -c bsd -e ${{ env.maintainer_mail }} --createorig -l -y
        # dh_make -f ../xeve-main.tar.gz -c bsd -e ${{ env.maintainer_mail }} --createorig -l -y

        echo "Debmail in package: ${{ env.debmail }}  :email:" >> $GITHUB_STEP_SUMMARY
        echo "Debfullname in package: ${{ env.debfullname }}  :speech_balloon:" >> $GITHUB_STEP_SUMMARY

    - name: Upload GPG key to launchpad.net
      # this step is currently disabled
      # https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow
      if: ${{ false }} 
      env:
        KEY_ID_SECRET: ${{ secrets.SuperSecret }}
      run:  gpg --keyserver "https://keyserver.ubuntu.com/#" --send-key $KEY_ID_SECRET


    - name: Edit sources (base)
      # TODO: Files from this step have to be later integrated with project repository, they shouldn't be fetched from external repo
      run: |
        cd xeve-base-${{ steps.vars.outputs.TAG }}/debian

        curl -o changelog https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/base/debian/changelog
        curl -o compat https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/base/debian/compat
        curl -o control https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/base/debian/control
        curl -o copyright https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/base/debian/copyright
        curl -o rules https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/base/debian/rules
        curl -o xeve-base-dev.install https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/base/debian/xeve-base-dev.install
        curl -o xeve-base1.install https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/base/debian/xeve-base1.install
        
    - name: Edit sources (main)
      # TODO: Files from this step have to be later integrated with project repository, they shouldn't be fetched from external repo
      if: ${{ false }}
      run: |
        cd xeve-main-${{ steps.vars.outputs.TAG }}/debian

        curl -o changelog https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/main/debian/changelog
        curl -o compat https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/main/debian/compat
        curl -o control https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/main/debian/control
        curl -o copyright https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/main/debian/copyright
        curl -o rules https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/main/debian/rules
        curl -o xeve-main-dev.install https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/main/debian/xeve-main-dev.install
        curl -o xeve-main1.install https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/main/debian/xeve-main1.install  
    
    - name: 'Upload executable Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: download
        path: xeve*
        retention-days: 1

    - name: Debuild
      run: |
        echo "::group::DEBUG"
        pwd 
        ls -al
        file xeve-base_0.4.3.orig.tar.gz
        echo "::endgroup::"
        
        cd xeve-base-${{ steps.vars.outputs.TAG }}
        pwd
        ls -al
        debuild -S -sa
        ls -al

    - name: Push package to launchpad
      # if: ${{ false }}
      run: |
        echo "::notice title={Launchpad push: }::This will push to Launchpad
        # dput ppa:wellsakus/hello hello_1.0.0-1_source.changes"
        #echo "Package placed on: PPA URL  :globe_with_meridians:" >> $GITHUB_STEP_SUMMARY



