# This workfow will upload package to launchpad.net

name: Launchpad

on:
  workflow_dispatch:

jobs:
  launchpad:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch sources from latest release
      id: vars
      run: |

        # https://geraldonit.com/2019/01/15/how-to-download-the-latest-github-repo-release-via-command-line/

        # get tag
        TAG=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest | grep "tag_name" | awk -F: '{print $2}' | cut -c 4- | cut -c -5)
        #get file location
        LOCATION=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest \
        | grep "tag_name" \
        | awk '{print "https://github.com/${GITHUB_REPOSITORY}archive/" substr($2, 2, length($2)-3) ".tar.gz"}')
        
        # #download file
        curl -L -o xeve.tar.gz $LOCATION

        echo "TAG: $TAG"
        echo "TAG=$TAG" >> $GITHUB_OUTPUT
        echo "-------------------------------------"

        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
        echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
        echo "GITHUB_ENV: $GITHUB_ENV"
        echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
        echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
        echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
        echo "GITHUB_WORKFLOW_REF: $GITHUB_WORKFLOW_REF"
        echo "RUNNER_NAME: $RUNNER_NAME"


        echo "-------------------------------------"
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "Tag name from github.ref_name: ${{  github.ref_name }}"
        #TODO: change below line
        mkdir xeve-$TAG
        ls -al
        pwd

    - name: Prepare package
      run: |
        sudo apt install dh-make
        ls -al
        pwd
        echo "-------------------------------------"
        echo "TAG: ${{ steps.vars.outputs.TAG }}"
        cd xeve-${{ steps.vars.outputs.TAG }}
        dh_make -f ../xeve.tar.gz -c bsd -e maintainer@example.com --createorig -l -y


