# This is a basic workflow that is manually triggered

name: Launchpad

on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  launchpad:
    runs-on: ubuntu-latest

    - name: Fetch all Github Release Assets
      uses: dsaltares/fetch-gh-release-asset@1.1.0
      with:
        regex: true
        file: "*"
        token: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Fetch Github Release Asset
      uses: dsaltares/fetch-gh-release-asset@1.1.0
      with:
        regex: true
        file: "*\\.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}



    - name: init
      run: |
        sudo apt install dh-make
        dh_make -c bsd -e maintainer@example.com --createorig -l

