# This workfow will upload package to launchpad.net

name: Launchpad

on:
  workflow_dispatch:

jobs:
  launchpad:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch sources from latest release
      run: |

        # https://geraldonit.com/2019/01/15/how-to-download-the-latest-github-repo-release-via-command-line/

        # get tag
        TAG=$(curl -s https://api.github.com/repos/dariusz-f/xeve/releases/latest | grep "tag_name" | awk -F- '{print $1}' | cut -c 16-)

        #get file location
        LOCATION=$(curl -s https://api.github.com/repos/dariusz-f/xeve/releases/latest \
        | grep "tag_name" \
        | awk '{print "https://github.com/dariusz-f/xeve/archive/" substr($2, 2, length($2)-3) ".tar.gz"}')
        
        # #download file
        curl -L -o sources-0.4.3.tar.gz $LOCATION

        echo $TAG
        echo $LOCATION
        ls -al

    - name: Prepare package
      run: |
        sudo apt install dh-make
        ls -al
        dh_make -f sources-0.4.3.tar.gz -c bsd -e maintainer@example.com --createorig -l


