# This workfow will upload package to launchpad.net

name: Launchpad

on:
  workflow_dispatch:

jobs:
  launchpad:
    runs-on: ubuntu-latest

    steps:
    - name: Set const values
      run: |
        echo "maintainer_mail=maintainer@example.com" >> $GITHUB_ENV

        #TODO: check below lines is they working correctly in actions workflow
        DEBEMAIL="${{ env.maintainer_mail }}"
        DEBFULLNAME="MPEG-5 EVC"
        export DEBEMAIL DEBFULLNAME

    - name: Get sources
      id: vars
      run: |
        #Get tag
        TAG=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest \
        | grep "tag_name" | awk -F: '{print $2}' | cut -c 4- | cut -c -5)
        echo "TAG=$TAG" >> $GITHUB_OUTPUT

        #Get sources (https://geraldonit.com/2019/01/15/how-to-download-the-latest-github-repo-release-via-command-line/)
        LOCATION=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest \
        | grep "tag_name" | awk '{print "https://github.com/${GITHUB_REPOSITORY}archive/" substr($2, 2, length($2)-3) ".tar.gz"}')

        #Download file
        curl -L -o xeve.tar.gz $LOCATION

        echo "::warning title={TAG: }::$TAG"

    - name: Install dependencies
      run: |
        sudo apt install packaging-dev gnupg fakeroot

    - name: Prepare package
      run: |
        mkdir xeve-${{ steps.vars.outputs.TAG }}
        cd xeve-${{ steps.vars.outputs.TAG }}
        dh_make -f ../xeve.tar.gz -c bsd -e ${{ env.maintainer_mail }} --createorig -l -y

    - name: Upload GPG key to launchpad.net
      # this step is currently disabled
      if: ${{ false }} 
      run:  gpg --keyserver "https://keyserver.ubuntu.com/#" --send-key ...ID...

    - name: Nex steps implementation TODO
      run: |
        pwd
        ls -al
        echo ${{ env.maintainer_mail }}
        echo ${{ steps.vars.outputs.TAG }}
        echo $DEBEMAIL $DEBFULLNAME

        debuild -S -sa

