# This workfow is responsbile for creating deb package and upload it to launchpad.net

name: Launchpad

on:
  workflow_dispatch:

jobs:
  launchpad:
    runs-on: ubuntu-latest

    steps:
    # Here golbal variables can be set!
    - name: Set const values
      run: |
        echo "maintainer_mail=maintainer@example.com" >> $GITHUB_ENV
        echo "debmail=maintainer@example.com" >> $GITHUB_ENV
        echo "debfullname=MPEG-5_EVC" >> $GITHUB_ENV

    - name: Get sources
      id: vars
      run: |
        #Get tag
        TAG=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest \
        | grep "tag_name" | awk -F: '{print $2}' | cut -c 4- | cut -c -5)
        echo "TAG=$TAG" >> $GITHUB_OUTPUT

        #Get sources (https://geraldonit.com/2019/01/15/how-to-download-the-latest-github-repo-release-via-command-line/)
        LOCATION=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest \
        | grep "tag_name" | awk '{print "https://github.com/${GITHUB_REPOSITORY}archive/" substr($2, 2, length($2)-3) ".tar.gz"}')

        #Download file
        curl -L -o xeve.tar.gz $LOCATION

        echo "::warning title={TAG: }::$TAG"

    - name: Install dependencies
      run: |
        sudo apt install packaging-dev gnupg

    - name: Prepare package
      run: |
        mkdir xeve-${{ steps.vars.outputs.TAG }}
        cd xeve-${{ steps.vars.outputs.TAG }}

        DEBMAIL=${{ env.debmail }}
        DEBFULLNAME=${{ env.debfullname }}
        export DEBEMAIL DEBFULLNAME
        dh_make -f ../xeve.tar.gz -c bsd -e ${{ env.maintainer_mail }} --createorig -l -y

    - name: Upload GPG key to launchpad.net
      # this step is currently disabled
      if: ${{ false }} 
      run:  gpg --keyserver "https://keyserver.ubuntu.com/#" --send-key ...ID...

    - name: Edit sources
      # Files from this step have to be later integrated with project repository
      run: |
        cd xeve-${{ steps.vars.outputs.TAG }}/debian

        curl -o changelog https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/base/debian/changelog
        curl -o control https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/base/debian/control
        curl -o copyright https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/base/debian/copyright
        curl -o rules https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/base/debian/rules
        curl -o xeve-base-dev.install https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/base/debian/xeve-base-dev.install
        curl -o xeve-base1.install https://raw.githubusercontent.com/dkozinski/xeve/debian-debian/debian/base/debian/xeve-base1.install

        ls -la
        cat changelog
        cat control
        cat xeve-base1.install

    - name: Debuild
      run: |
        pwd
        ls -al
        cd xeve-${{ steps.vars.outputs.TAG }}
        ls -al
        debuild -S -sa
        ls -al

    - name: Push package to launchpad
      # if: ${{ false }}
      run: |
        echo "::warning title={Launchpad push: }::This will push to Launchpad
        # dput ppa:wellsakus/hello hello_1.0.0-1_source.changes"



